# .github/labeler.yml
#
# This file is intended for automatic PR labeling (via a GitHub App or an Action).

"src/**":         ["area:contracts"]
"script/**":      ["area:scripts"]
"test/**":        ["area:tests"]
"docs/**":        ["docs"]
".github/**":     ["area:ci"]
"foundry.toml":   ["area:build"]
"deployments/**": ["area:deploy"]
