name: Feature request
description: Propose an improvement for BlackCat Kernel Contracts
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline the change and which contract(s) it affects.
  - type: textarea
    id: notes
    attributes:
      label: Notes / alternatives

